version: '2'
services:
  # Service for nameserver
  rmq-namesrv:
    image: apache/rocketmq:latest
    container_name: rmq-namesrv
    ports:
      - 9876:9876
    volumes:
      - ./logs/namesrv:/home/rocketmq/logs
    command: sh mqnamesrv

  # Service for broker0
  rmq-broker0:
    image: apache/rocketmq:latest
    container_name: rmq-broker0
    links:
      - rmq-namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./logs/broker0:/home/rocketmq/logs
      - ./store/broker0:/home/rocketmq/store
      - ./conf/broker0.conf:/opt/rocketmq-latest/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-latest/conf/broker.conf

  # Service for broker1
  rmq-broker1:
    image: apache/rocketmq:latest
    container_name: rmq-broker1
    links:
      - rmq-namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./logs/broker1:/home/rocketmq/logs
      - ./store/broker1:/home/rocketmq/store
      - ./conf/broker1.conf:/opt/rocketmq-latest/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-latest/conf/broker.conf

  # Service for dashboard
  rmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmq-dashboard
    links:
      - rmq-namesrv
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876

  # Service for go client
  rmq-client-go:
    image: golang:latest
    container_name: rmq-client-go
    links:
      - rmq-namesrv
    volumes:
      - $PWD:/usr/src/play-rocketmq
    working_dir: /usr/src/play-rocketmq
    tty: true
    command: bash
